config/routes.rb
Rails.application.routes.draw do
  resources :articulos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  # GET /articulos
  # GET /articulos.json
  def index
    @articulos = Articulo.all
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo was successfully created.' }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1
  # PATCH/PUT /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: 'Articulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url, notice: 'Articulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articulo_params
      params.require(:articulo).permit(:titulo, :cuerpo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/views/articulos/_form.html.erb
<%= form_with(model: articulo, local: true) do |form| %>
  <% if articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
      <% articulo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :articulo_titulo %>
  </div>

  <div class="field">
    <%= form.label :cuerpo %>
    <%= form.text_area :cuerpo, id: :articulo_cuerpo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<h1>Editing Articulo</h1>

<%= render 'form', articulo: @articulo %>

<%= link_to 'Show', @articulo %> |
<%= link_to 'Back', articulos_path %>

app/views/articulos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articulos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Cuerpo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulos.each do |articulo| %>
      <tr>
        <td><%= articulo.titulo %></td>
        <td><%= articulo.cuerpo %></td>
        <td><%= link_to 'Show', articulo %></td>
        <td><%= link_to 'Edit', edit_articulo_path(articulo) %></td>
        <td><%= link_to 'Destroy', articulo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Articulo', new_articulo_path %>

app/views/articulos/new.html.erb
<h1>New Articulo</h1>

<%= render 'form', articulo: @articulo %>

<%= link_to 'Back', articulos_path %>

app/views/articulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @articulo.titulo %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @articulo.cuerpo %>
</p>

<%= link_to 'Edit', edit_articulo_path(@articulo) %> |
<%= link_to 'Back', articulos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Normal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>